help:
	@echo "Available commands:"
	@echo "  init                - Set up development tools and Python virtual environment"
	@echo "  deploy              - Build and deploy all services"
	@echo "  deploy-service      - Build and deploy specific service"
	@echo "  destroy             - Destroy all services"
	@echo "  destroy-service     - Destroy specific services"
	@echo "  lint                - Lint all services"
	@echo "  test                - Test all services"
	@echo "  help                - Show this help message"
	@echo "  requirements        - Install Python requirements"
